"""empty message

Revision ID: 43914e4334c4
Revises: 
Create Date: 2023-12-28 07:17:23.097508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43914e4334c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
